package com.example.yhxct.mapper;

import com.example.yhxct.model.MStudent;
import com.example.yhxct.model.MStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @SelectProvider(type=MStudentSqlProvider.class, method="countByExample")
    long countByExample(MStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @DeleteProvider(type=MStudentSqlProvider.class, method="deleteByExample")
    int deleteByExample(MStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @Insert({
        "insert into student (uuid, name, ",
        "age)",
        "values (#{uuid,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER})"
    })
    int insert(MStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @InsertProvider(type=MStudentSqlProvider.class, method="insertSelective")
    int insertSelective(MStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @SelectProvider(type=MStudentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="uuid", property="uuid", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER)
    })
    List<MStudent> selectByExample(MStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @UpdateProvider(type=MStudentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MStudent record, @Param("example") MStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Tue Aug 20 15:51:58 CST 2019
     */
    @UpdateProvider(type=MStudentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MStudent record, @Param("example") MStudentExample example);
}